---
kind: workerService
version: udx.io/worker-v1/service
services:
  - name: sshd
    command: /usr/sbin/sshd -D -f /etc/ssh/sshd_config -e
    autostart: true
    autorestart: true
    envs:
      - DEBUG=ssh:*,auth:*
    # max_restarts: 50
    # restart_delay: 10000
    # log_date_format: YYYY-MM-DD HH:mm Z
    
  - name: k8gate
    command: node /opt/sources/k8gate/server/bin/server.js 2>&1 | tee -a /var/log/k8gate.log
    autostart: true
    autorestart: true
    envs:
      - DEBUG=k8gate:*,api:*,auth:*
      - NODE_ENV=production
      - PORT=8080
      - NODE_PORT=8080
    # max_memory_restart: 512M
    # max_restarts: 50
    # restart_delay: 10000
    # log_date_format: YYYY-MM-DD HH:mm Z
    healthcheck:
      http:
        port: ${NODE_PORT}
        path: /health
        interval: 10s
        timeout: 3s
        retries: 2
    
  # Firebase events service removed

  - name: ssh-keys-sync
    command: node /usr/local/bin/controller.keys.js 2>&1 | tee -a /var/log/ssh-keys-sync.log
    autostart: ${SERVICE_ENABLE_SSHD}
    autorestart: true
    envs:
      - DEBUG=ssh:keys:*,auth:*
      - DIRECTORY_KEYS_BASE=/etc/ssh/authorized_keys.d
      - PASSWORD_FILE=/etc/passwd
      - PASSWORDS_TEMPLATE=alpine.passwords
    depends_on:
      - sshd
    interval: 300  # Run every 5 minutes
    max_restarts: 0  # No limit on restarts
    restart_delay: 10000  # Wait 10s between restarts
