version: "1.0"
services:
  - name: "sshd"
    command: "/usr/sbin/sshd -D -f /etc/ssh/sshd_config -e"
    autostart: true
    autorestart: true
    user: "root"
    envs:
      - "DEBUG=ssh:*,auth:*"
      - "HOME=/root"

  - name: "k8gate"
    command: "/usr/local/bin/node /opt/sources/rabbitci/rabbit-ssh/bin/server.js"
    autostart: true
    autorestart: true
    user: "udx"
    cwd: "/opt/sources/rabbitci/rabbit-ssh"
    envs:
      - "DEBUG=k8gate:*,api:*,auth:*,ssh:*"
      - "NODE_ENV=test"
      - "PORT=8080"
      - "NODE_PORT=8080"
      - "HOME=/home/udx"
      - "SERVICE_ENABLE_API=true"
      - "SERVICE_ENABLE_SSHD=true"
    healthcheck:
      http:
        port: 8080
        path: "/health"
        interval: 30
        timeout: 10
        retries: 3

  - name: "ssh-keys-sync"
    command: "/usr/local/bin/node /opt/sources/rabbitci/rabbit-ssh/bin/controller.keys.js"
    autostart: true
    autorestart: true
    user: "udx"
    cwd: "/opt/sources/rabbitci/rabbit-ssh"
    envs:
      - "DEBUG=ssh:keys:*,auth:*"
      - "DIRECTORY_KEYS_BASE=/etc/ssh/authorized_keys.d"
      - "PASSWORD_FILE=/etc/passwd"
      - "PASSWORDS_TEMPLATE=alpine.passwords"
      - "HOME=/home/udx"
    depends_on:
      - "sshd"
    interval: 300
