services:
  - name: sshd
    command: /usr/sbin/sshd -D -f /etc/ssh/sshd_config -e
    autostart: ${SERVICE_ENABLE_SSHD}
    autorestart: true
    envs:
      - DEBUG=ssh:*,auth:*
  
  - name: k8gate
    command: node /opt/sources/rabbitci/rabbit-ssh/bin/server.js
    autostart: ${SERVICE_ENABLE_API}
    autorestart: true
    envs:
      - DEBUG=k8gate:*,api:*,auth:*
      - NODE_ENV=production
      - PORT=8080
      
  - name: ssh_keys_sync
    command: node /opt/sources/rabbitci/rabbit-ssh/bin/controller.keys.js
    autostart: ${SERVICE_ENABLE_SSHD}
    autorestart: true
    envs:
      - DEBUG=ssh:keys:*,auth:*
      - DIRECTORY_KEYS_BASE=/etc/ssh/authorized_keys.d
      - PASSWORD_FILE=/etc/passwd
      - PASSWORDS_TEMPLATE=alpine.passwords
