---
kind: workerConfig
version: udx.io/worker-v1/config
config:
  env:
    NODE_ENV: ${NODE_ENV}
    PORT: ${PORT}
    NODE_PORT: ${NODE_PORT}
    SERVICE_ENABLE_SSHD: ${SERVICE_ENABLE_SSHD}
    SERVICE_ENABLE_API: ${SERVICE_ENABLE_API}
    SERVICE_ENABLE_FIREBASE: ${SERVICE_ENABLE_FIREBASE}
    USE_GKE_GCLOUD_AUTH_PLUGIN: ${USE_GKE_GCLOUD_AUTH_PLUGIN}
