---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8-container-gate
  labels:
    app: k8-container-gate
    git.name: k8-container-gate
    git.owner: usabilitydynamics
    git.branch: master
spec:
  selector:
    matchLabels:
      app: k8-container-gate
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: k8-container-gate
        git.name: k8-container-gate
        git.owner: usabilitydynamics
        git.branch: master
      annotations:
        container.apparmor.security.beta.kubernetes.io/k8-container-gate: runtime/default
    spec:
      serviceAccountName: k8-container-gate
      containers:
        - name: k8-container-gate
          image: usabilitydynamics/k8-container-gate:latest
          imagePullPolicy: Always
          ports:
            - name: ssh
              containerPort: 22
            - name: api
              containerPort: 8080
          resources: 
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
            - name: NODE_PORT
              value: "8080"
            - name: SERVICE_ENABLE_SSHD
              value: "true"
            - name: SERVICE_ENABLE_API
              value: "true"
            # Firebase integration removed
            - name: USE_GKE_GCLOUD_AUTH_PLUGIN
              value: "true"
            - name: DEBUG
              value: k8gate:*,api:*,auth:*,ssh:*,sftp:*
            - name: KUBERNETES_CLUSTER_NAME
              value: ${KUBERNETES_CLUSTER_NAME}
            - name: KUBERNETES_CLUSTER_NAMESPACE
              value: ${KUBERNETES_CLUSTER_NAMESPACE}
            - name: KUBERNETES_CLUSTER_ENDPOINT
              value: https://${KUBERNETES_CLUSTER_ENDPOINT}
            - name: KUBERNETES_CLUSTER_SERVICEACCOUNT
              value: ${KUBERNETES_CLUSTER_SERVICEACCOUNT}
            - name: KUBERNETES_CLUSTER_CONTEXT
              value: ${KUBERNETES_CLUSTER_CONTEXT}
            - name: ALLOW_SSH_ACCESS_ROLES
              value: ${ALLOW_SSH_ACCESS_ROLES}
          volumeMounts:
            - name: ssh-keys
              mountPath: /etc/ssh/authorized_keys.d
            - name: worker-config
              mountPath: /home/udx/.cd/configs
            - name: services-config
              mountPath: /etc/worker
            - name: logs
              mountPath: /var/log
          livenessProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
      volumes:
        - name: ssh-keys
          emptyDir: {}
        - name: worker-config
          configMap:
            name: k8-container-gate-worker-config
        - name: services-config
          configMap:
            name: k8-container-gate-services-config
        - name: logs
          emptyDir: {}
