apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-sftp
  labels:
    app: docker-sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-sftp
  template:
    metadata:
      labels:
        app: docker-sftp
    spec:
      containers:
      - name: docker-sftp
        image: usabilitydynamics/docker-sftp:latest
        ports:
        - containerPort: 22
        volumeMounts:
        - name: ssh-keys
          mountPath: /etc/ssh/authorized_keys.d
        - name: worker-config
          mountPath: /home/udx/.cd/configs
        env:
        - name: KUBERNETES_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: docker-sftp-config
              key: cluster_name
        - name: KUBERNETES_CLUSTER_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: docker-sftp-config
              key: namespace
        - name: SERVICE_ENABLE_SSHD
          value: "true"
        - name: SERVICE_ENABLE_API
          value: "true"
        envFrom:
        - secretRef:
            name: docker-sftp-secrets
      volumes:
      - name: ssh-keys
        emptyDir: {}
      - name: worker-config
        configMap:
          name: docker-sftp-worker-config
---
apiVersion: v1
kind: Service
metadata:
  name: docker-sftp
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 22
  selector:
    app: docker-sftp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-sftp-config
data:
  cluster_name: "${KUBERNETES_CLUSTER_NAME}"
  namespace: "${KUBERNETES_CLUSTER_NAMESPACE}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-sftp-worker-config
data:
  worker.yml: |
    kind: workerConfig
    version: udx.io/worker-v1/config
    config:
      env:
        NODE_ENV: "production"
        SERVICE_ENABLE_SSHD: "true"
        SERVICE_ENABLE_API: "true"
        DEBUG: "ssh:*"
      secrets:
        KUBERNETES_CLUSTER_ENDPOINT: "azure/k8s-secrets/cluster-endpoint"
        KUBERNETES_CLUSTER_USER_TOKEN: "azure/k8s-secrets/user-token"
        ACCESS_TOKEN: "azure/github/access-token"
