---
apiVersion: v1
kind: Service
metadata:
  name: k8-container-gate
  labels:
    app: k8-container-gate
    git.name: k8-container-gate
    git.owner: usabilitydynamics
    git.branch: master
spec:
  type: LoadBalancer
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: api
      port: 8080
      targetPort: 8080
  selector:
    app: k8-container-gate
    git.name: k8-container-gate
    git.branch: master
