---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}-${IMAGE_BRANCH}
  labels:
    name: ${CIRCLE_PROJECT_REPONAME}-${IMAGE_BRANCH}
    git.name: ${CIRCLE_PROJECT_REPONAME}
    git.owner: ${CIRCLE_PROJECT_USERNAME}
    git.branch: ${IMAGE_BRANCH}
spec:
  # how many pods and indicate which strategy we want for rolling update
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        name: ${CIRCLE_PROJECT_REPONAME}-${IMAGE_BRANCH}
        git.name: ${CIRCLE_PROJECT_REPONAME}
        git.owner: ${CIRCLE_PROJECT_USERNAME}
        git.branch: ${IMAGE_BRANCH}
      annotations:
        container.apparmor.security.beta.kubernetes.io/sftp: runtime/default
    spec:
      serviceAccountName: "${GKE_NAMESPACE_SA}"
      containers:
        - name: sftp
          image: "${IMAGE_REPO}/${TARGET}:${IMAGE_TAG}"
          imagePullPolicy: Always
          ports:
            - name: ssh
              containerPort: 22
          resources: {}
          livenessProbe:
            tcpSocket:
              port: ssh
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: ssh
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
            successThreshold: 1