title: UDX Engineering Blog
description: Insights and experiences from the UDX engineering team
baseurl: "/docker-sftp"
url: "https://andypotanin.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author settings
author:
  name: UDX Team
  email: team@udx.io

# Social links
github_username: andypotanin
twitter_username: udx

# Markdown settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
