name: Build and Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npm install --save-dev jest eslint eslint-plugin-node
    
    - name: Run linting
      run: npm run lint
    
    - name: Set Tag from package.json
      id: version
      run: echo "TAG=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
    
    - name: Build Docker image
      env:
        REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      run: |
        docker build \
          --tag ${REGISTRY}/${IMAGE_NAME}:${{ steps.version.outputs.TAG }} \
          --build-arg NODE_ENV=test \
          -f Dockerfile.udx .
    
    - name: Save Docker image
      env:
        REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      run: |
        docker save ${REGISTRY}/${IMAGE_NAME}:${{ steps.version.outputs.TAG }} > /tmp/docker-image.tar
    
    - name: Upload Docker image
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: /tmp/docker-image.tar
        retention-days: 1
