name: Build and Test Container

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run linting
      run: npm run lint
    
    - name: Set Tag from package.json
      id: version
      run: echo "TAG=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Pull base image
      run: docker pull usabilitydynamics/udx-worker-nodejs:latest || docker pull node:20-slim
    
    - name: Build base image if needed
      if: failure()
      run: |
        # Create temporary Dockerfile for base image
        cat > Dockerfile.base << 'EOF'
        FROM node:20-slim
        
        # Create udx user and group
        RUN groupadd -r udx && useradd -r -g udx -m udx
        
        # Create necessary directories
        RUN mkdir -p /etc/worker && chown -R udx:udx /etc/worker
        
        # Set working directory
        WORKDIR /opt/sources
        
        # Switch to udx user
        USER udx
        EOF
        
        # Build and push base image
        docker build -t usabilitydynamics/udx-worker-nodejs:latest -f Dockerfile.base .
        docker push usabilitydynamics/udx-worker-nodejs:latest
    
    - name: Build Docker image
      env:
        REGISTRY: usabilitydynamics
        IMAGE_NAME: k8-container-gate
      run: |
        docker build \
          --tag ${REGISTRY}/${IMAGE_NAME}:${{ steps.version.outputs.TAG }} \
          --tag ${REGISTRY}/${IMAGE_NAME}:latest \
          --build-arg NODE_ENV=test \
          -f Dockerfile.udx .
    
    - name: Test container startup and services
      env:
        REGISTRY: usabilitydynamics
        IMAGE_NAME: k8-container-gate
      run: |
        # Create test SSH key
        ssh-keygen -t rsa -f /tmp/test_key -N ""
        
        # Start container with test configuration
        docker run -d --name test-container \
          -e NODE_ENV=test \
          -e SERVICE_ENABLE_SSHD=true \
          -e SERVICE_ENABLE_API=true \
          -e DEBUG=ssh:* \
          -e SERVICE_ENABLE_K8S=false \
          -e SERVICE_ENABLE_FIREBASE=false \
          -p 2222:22 \
          -p 8080:8080 \
          ${REGISTRY}/${IMAGE_NAME}:${{ steps.version.outputs.TAG }}
        
        # Wait for container to start
        sleep 15
        
        # Get container logs
        docker logs test-container
        
        # Check if sshd is running and properly configured
        docker exec test-container sh -c '
          # Verify sshd process
          pgrep sshd || exit 1
          
          # Check sshd config
          sshd -t || exit 1
          
          # Verify SSH directory permissions
          test -d /etc/ssh/authorized_keys.d || exit 1
          test "$(stat -c %a /etc/ssh/authorized_keys.d)" = "755" || exit 1
        '
        
        # Check if API server is running
        docker exec test-container sh -c '
          # Verify Node process
          pgrep node || exit 1
          
          # Check API server port
          netstat -tlpn | grep :8080 || exit 1
        '
        
        # Test API server health endpoint
        curl -f http://localhost:8080/health || exit 1
        
        # Test SSH connection
        docker cp /tmp/test_key.pub test-container:/etc/ssh/authorized_keys.d/test-user
        docker exec test-container chmod 644 /etc/ssh/authorized_keys.d/test-user
        
        # Verify SSH port is open
        nc -zv localhost 2222 || exit 1

    - name: Push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        REGISTRY: usabilitydynamics
        IMAGE_NAME: k8-container-gate
      run: |
        # Push both tagged and latest versions
        docker push ${REGISTRY}/${IMAGE_NAME}:${{ steps.version.outputs.TAG }}
        docker push ${REGISTRY}/${IMAGE_NAME}:latest

    - name: Save Docker image
      run: |
        docker save ${REGISTRY}/${IMAGE_NAME}:${{ steps.version.outputs.TAG }} > /tmp/docker-image.tar
    
    - name: Upload Docker image
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: /tmp/docker-image.tar
        retention-days: 1
