name: Build and Test Container

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run linting
      run: npm run lint
    
    - name: Set Tag from package.json
      id: version
      run: echo "TAG=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Pull base image
      run: docker pull usabilitydynamics/udx-worker-nodejs:latest
    
    - name: Build Docker image
      run: |
        # Build Docker image with version tag
        docker build \
          --tag sftp-gateway:${{ steps.version.outputs.TAG }} \
          --tag sftp-gateway:latest \
          --build-arg NODE_ENV=test \
          --build-arg SERVICE_ENABLE_SSHD=true \
          --build-arg SERVICE_ENABLE_API=true \
          --build-arg WORKER_DEBUG=true \
          -f Dockerfile.udx .
    
    - name: Test container startup and services
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KUBERNETES_CLUSTER_ENDPOINT: https://test-cluster:6443
        KUBERNETES_CLUSTER_NAME: test-cluster
        KUBERNETES_CLUSTER_NAMESPACE: test-namespace
        KUBERNETES_CLUSTER_USER_TOKEN: test-user-token
        KUBERNETES_CLUSTER_SERVICEACCOUNT: test-serviceaccount
        KUBERNETES_CLUSTER_CERTIFICATE: test-cert
        KUBERNETES_CLUSTER_USER_SECRET: test-secret
        KUBERNETES_CLUSTER_CONTEXT: test-context
        ALLOW_SSH_ACCESS_ROLES: admin,maintain,write
      run: |
        # Create test SSH key and directories
        sudo mkdir -p /etc/ssh/authorized_keys.d
        sudo chmod 755 /etc/ssh/authorized_keys.d
        ssh-keygen -t rsa -f /tmp/test_key -N ""
        sudo cp /tmp/test_key.pub /etc/ssh/authorized_keys.d/test-user
        sudo chmod 644 /etc/ssh/authorized_keys.d/test-user

        # Install supervisord
        sudo apt-get update
        sudo apt-get install -y supervisor

        # Set up supervisord configuration
        echo "Setting up supervisord configuration..."
        sudo mkdir -p /etc/supervisor/conf.d /var/log/supervisor
        sudo cp static/etc/supervisor/supervisord.conf /etc/supervisor/supervisord.conf
        sudo cp static/etc/supervisor/services.conf /etc/supervisor/conf.d/
        sudo chmod 755 /etc/supervisor/conf.d
        sudo chmod 644 /etc/supervisor/conf.d/services.conf
        sudo chmod 644 /etc/supervisor/supervisord.conf
        sudo chown -R root:root /etc/supervisor
        
        # Create and set up log files
        sudo mkdir -p /var/log/{supervisor,sshd,k8gate}
        sudo touch /var/log/{supervisor/supervisord,sshd,k8gate,ssh-keys-sync,auth}.log
        sudo chown -R udx:udx /var/log/{sshd,k8gate,ssh-keys-sync,auth}.log
        sudo chmod 644 /var/log/{sshd,k8gate,ssh-keys-sync,auth}.log
        
        echo "Supervisord configuration contents:"
        cat /etc/supervisor/supervisord.conf
        echo "Services configuration:"
        cat /etc/supervisor/conf.d/services.conf
        
        echo "Log directory structure:"
        ls -la /var/log/
        
        echo "Testing supervisord configuration..."
        docker run --rm \
          -v /etc/supervisor:/etc/supervisor:ro \
          -v /var/log:/var/log \
          -e NODE_ENV=test \
          -e SERVICE_ENABLE_SSHD=true \
          -e SERVICE_ENABLE_API=true \
          sftp-gateway:${{ steps.version.outputs.TAG }} \
          supervisord -c /etc/supervisor/supervisord.conf -n -t

        # Create test container with proper mounts and environment
        
        # Create test container with proper mounts
        docker create --name test-container \
          --privileged \
          -e NODE_ENV=test \
          -e SERVICE_ENABLE_SSHD=true \
          -e SERVICE_ENABLE_API=true \
          -e DEBUG=k8gate:*,api:*,auth:*,ssh:*,worker:* \
          -e SERVICE_ENABLE_K8S=false \
          -v /etc/supervisor:/etc/supervisor:ro \
          -e ACCESS_TOKEN=${ACCESS_TOKEN} \
          -e KUBERNETES_CLUSTER_ENDPOINT=${KUBERNETES_CLUSTER_ENDPOINT} \
          -e KUBERNETES_CLUSTER_NAME=${KUBERNETES_CLUSTER_NAME} \
          -e KUBERNETES_CLUSTER_NAMESPACE=${KUBERNETES_CLUSTER_NAMESPACE} \
          -e KUBERNETES_CLUSTER_USER_TOKEN=${KUBERNETES_CLUSTER_USER_TOKEN} \
          -e KUBERNETES_CLUSTER_SERVICEACCOUNT=${KUBERNETES_CLUSTER_SERVICEACCOUNT} \
          -e KUBERNETES_CLUSTER_CERTIFICATE=${KUBERNETES_CLUSTER_CERTIFICATE} \
          -e KUBERNETES_CLUSTER_USER_SECRET=${KUBERNETES_CLUSTER_USER_SECRET} \
          -e KUBERNETES_CLUSTER_CONTEXT=${KUBERNETES_CLUSTER_CONTEXT} \
          -e ALLOW_SSH_ACCESS_ROLES=${ALLOW_SSH_ACCESS_ROLES} \
          -e DIRECTORY_KEYS_BASE=/etc/ssh/authorized_keys.d \
          -e PASSWORD_FILE=/etc/passwd \
          -e PASSWORDS_TEMPLATE=alpine.passwords \
          -e STATE_PROVIDER=local \
          -v /etc/ssh/authorized_keys.d:/etc/ssh/authorized_keys.d:ro \
          -v /var/log:/var/log \
          -p 2222:22 \
          -p 8080:8080 \
          sftp-gateway:${{ steps.version.outputs.TAG }}

        # Start the container
        echo "Starting container..."
        docker start test-container
        
        # Wait for container to initialize
        sleep 5
        
        # Verify supervisord configuration and service status
        echo "Verifying supervisord configuration and services..."
        docker exec test-container sh -c '
          echo "Supervisord version:"
          supervisord --version
          
          echo "\nSupervisord configuration:"
          ls -la /etc/supervisor/conf.d/
          cat /etc/supervisor/conf.d/services.conf
          
          echo "\nValidating configuration:"
          supervisord -c /etc/supervisor/supervisord.conf -n -t
          
          echo "\nStarting supervisord:"
          supervisord -c /etc/supervisor/supervisord.conf
          sleep 5
          
          echo "\nChecking service status:"
          supervisorctl status
        '
        
        # Wait for container to start and show logs
        sleep 5
        docker logs test-container
        
        # Test SSH daemon
        docker exec test-container pgrep sshd || exit 1
        
        # Test API server
        curl -f http://localhost:8080/health || exit 1
        
        # Test SSH key setup
        docker exec test-container test -f /etc/ssh/authorized_keys.d/test-user || exit 1
        docker exec test-container test -f /etc/passwd || exit 1
        
        # Test SSH configuration and worker setup
        docker exec test-container sh -c '
          # Check sshd config
          sshd -t || exit 1
          
          # Verify SSH directory permissions
          test -d /etc/ssh/authorized_keys.d || exit 1
          test "$(stat -c %a /etc/ssh/authorized_keys.d)" = "755" || exit 1
          
          # Verify key file permissions
          test -f /etc/ssh/authorized_keys.d/test-user || exit 1
          test "$(stat -c %a /etc/ssh/authorized_keys.d/test-user)" = "644" || exit 1

          # Verify supervisord configuration
          echo "Supervisord configuration:"
          ls -la /etc/supervisor/conf.d/
          cat /etc/supervisor/conf.d/services.conf
          
          # Test supervisord configuration
          echo "Testing supervisord configuration..."
          supervisord -c /etc/supervisor/supervisord.conf -n -t || exit 1
          
          # Check service status
          echo "Service status:"
          supervisorctl status || exit 1
          
          # Verify supervisord configuration
          test -d /etc/supervisor/conf.d || exit 1
          test -f /etc/supervisor/conf.d/services.conf || exit 1
          test "$(stat -c %a /etc/supervisor/conf.d)" = "755" || exit 1
          test "$(stat -c %a /etc/supervisor/conf.d/services.conf)" = "644" || exit 1
          
          # Verify services are running using supervisorctl
          supervisorctl status sshd | grep -q "RUNNING" || {
            echo "ERROR: SSHD service not running"
            supervisorctl status
            exit 1
          }
          
          supervisorctl status k8gate | grep -q "RUNNING" || {
            echo "ERROR: K8Gate API service not running"
            supervisorctl status
            exit 1
          }
          
          supervisorctl status ssh_keys_sync | grep -q "RUNNING" || {
            echo "ERROR: SSH key sync service not running"
            supervisorctl status
            exit 1
          }
          
          # Check service logs exist and have proper permissions
          for log_file in sshd k8gate ssh-keys-sync; do
            test -f "/var/log/${log_file}.log" || {
              echo "ERROR: ${log_file} log file missing"
              ls -la /var/log/
              exit 1
            }
            test "$(stat -c %a /var/log/${log_file}.log)" = "644" || {
              echo "ERROR: ${log_file} log has wrong permissions"
              ls -la "/var/log/${log_file}.log"
              exit 1
            }
          done
          
          # Check API health endpoint
          curl -sf http://localhost:8080/health || {
            echo "ERROR: API health check failed"
            curl -v http://localhost:8080/health || true
            exit 1
          }
          
          # Verify process ownership
          ps aux | grep "/usr/sbin/sshd -D" | grep -q "^root" || {
            echo "ERROR: SSHD not running as root"
            ps aux | grep sshd
            exit 1
          }
          ps aux | grep "node.*server.js\|controller.keys.js" | grep -q "^udx" || {
            echo "ERROR: Node.js processes not running as udx user"
            ps aux | grep "node"
            exit 1
          }
        ' || exit 1
        
        # Cleanup
        docker stop test-container
        docker rm test-container

    - name: Push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        REGISTRY: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: |
        # Tag for Docker Hub
        docker tag sftp-gateway:${{ steps.version.outputs.TAG }} ${REGISTRY}/k8-container-gate:${{ steps.version.outputs.TAG }}
        docker tag sftp-gateway:latest ${REGISTRY}/k8-container-gate:latest
        # Push to Docker Hub
        docker push ${REGISTRY}/k8-container-gate:${{ steps.version.outputs.TAG }}
        docker push ${REGISTRY}/k8-container-gate:latest
