name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
      - main

env:
  DOCKER_REPO_PATH: ${{ vars.DOCKER_REPO_PATH }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.udx
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKER_REPO_PATH }}:${{ steps.version.outputs.TAG }}
            ${{ env.DOCKER_REPO_PATH }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify image
        if: github.event_name != 'pull_request'
        run: |
          docker pull ${{ env.DOCKER_REPO_PATH }}:${{ steps.version.outputs.TAG }}
          docker inspect ${{ env.DOCKER_REPO_PATH }}:${{ steps.version.outputs.TAG }}
