name: 🚀 Deploy to Cloud Run

# Purpose: Deploys the container to Google Cloud Run
# Trigger: On successful Docker build or manual dispatch
# Output: Running service on Cloud Run with proper configuration

on:
  workflow_run:
    workflows: ["🐳 Docker Image Builder"]
    types:
      - completed
    branches:
      - master
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: k8-container-gate
  REGION: us-central1

jobs:
  deploy:
    name: 🌩️ Deploy to Cloud Run
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 🔑 Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: 🔧 Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'

      - name: 🚀 Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: usabilitydynamics/k8-container-gate:latest
          flags: |
            --port=3000
            --memory=512Mi
            --cpu=1
            --min-instances=0
            --max-instances=10
            --execution-environment=gen2
            --ingress=internal-and-cloud-load-balancing
            --session-affinity
            --set-env-vars=SERVICE_ENABLE_API=true,SERVICE_ENABLE_SSHD=true
            --set-env-vars=K8S_CLUSTER=${{ secrets.GKE_CLUSTER_NAME }}
            --set-env-vars=K8S_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            --set-env-vars=K8S_LOCATION=${{ secrets.GKE_CLUSTER_LOCATION }}
            --set-env-vars=K8S_NAMESPACE=${{ secrets.KUBERNETES_CLUSTER_NAMESPACE }}
            --set-env-vars=ALLOW_SSH_ACCESS_ROLES=admin
            --service-account=${{ secrets.K8S_SERVICE_ACCOUNT }}
            --tag=v0-9-0

      - name: 📝 Show Output
        run: echo ${{ steps.deploy.outputs.url }}
