name: Publish to DockerHub

on:
  workflow_run:
    workflows: ["Build and Test Container"]
    types:
      - completed
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set Tag from package.json
      id: version
      run: echo "TAG=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
    
    - name: Download Docker image
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: Build and Test Container
        workflow_conclusion: success
        name: docker-image
        path: /tmp
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Load Docker image
      run: docker load --input /tmp/docker-image.tar
    
    - name: Configure Docker Registry
      run: |
        echo "ucnehrtvflhbvyzf" | docker login -u "andypotanin" --password-stdin
        
    - name: Push to Docker Hub
      env:
        REGISTRY: usabilitydynamics
        IMAGE_NAME: k8-container-gate
      run: |
        # Push version tag
        docker tag ${REGISTRY}/${IMAGE_NAME}:${{ steps.version.outputs.TAG }} ${REGISTRY}/${IMAGE_NAME}:${{ steps.version.outputs.TAG }}
        docker push ${REGISTRY}/${IMAGE_NAME}:${{ steps.version.outputs.TAG }}
        
        # Tag and push latest
        docker tag ${REGISTRY}/${IMAGE_NAME}:${{ steps.version.outputs.TAG }} ${REGISTRY}/${IMAGE_NAME}:latest
        docker push ${REGISTRY}/${IMAGE_NAME}:latest
        
        # If this is a tag, also push the git tag version
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          docker tag ${REGISTRY}/${IMAGE_NAME}:${{ steps.version.outputs.TAG }} ${REGISTRY}/${IMAGE_NAME}:${VERSION}
          docker push ${REGISTRY}/${IMAGE_NAME}:${VERSION}
        fi
